import { supabase } from './supabaseClient.js';

function toYMD(date = new Date()) {
  // YYYY-MM-DD (local)
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

// This file writes to the following existing Supabase tables:
// - login
// - attendance_completions
// - app_logs
//
// Assumptions based on your provided schema:
// login fields: id (uuid), created_at (auto), Location (text), Emp_name (text), IP (text)
// attendance_completions fields: id (uuid), created_at (auto), Location (text), device_id (text), "Employee name" (text)
//
// IMPORTANT:
// - created_at is autogenerated in Supabase.
// - We do NOT send created_at.

// NOTE: The `day` parameter is intentionally ignored for now because your actual schema
// (as you provided) does not include a login_day/attendance_day column.

export async function upsertLoginActivity({ location, employeeName, ip } = {}) {
  if (!location) throw new Error('location is required');
  if (!employeeName) throw new Error('employeeName is required');
  if (!ip) throw new Error('ip is required');

  // Since your schema description does not list a unique constraint,
  // we do a plain insert.
  const { error } = await supabase.from('login').insert({
    Location: String(location),
    Emp_name: String(employeeName),
    IP: String(ip),
  });

  if (error) throw error;
  return { ok: true };
}

export async function upsertAttendanceCompletion({ location, deviceId, employeeName } = {}) {
  if (!location) throw new Error('location is required');
  if (!deviceId) throw new Error('deviceId is required');
  if (!employeeName) throw new Error('employeeName is required');

  // Since your schema description does not list a unique constraint,
  // we do a plain insert.
  const { error } = await supabase.from('attendance_completions').insert({
    Location: String(location),
    device_id: String(deviceId),
    'Employee name': String(employeeName),
  });

  if (error) throw error;
  return { ok: true };
}

export async function isAttendanceCompletedForDevice({ deviceId } = {}) {
  if (!deviceId) throw new Error('deviceId is required');

  // Without a date column in the provided schema, we can only check existence.
  const { data, error } = await supabase
    .from('attendance_completions')
    .select('id')
    .eq('device_id', String(deviceId))
    .maybeSingle();

  if (error) throw error;
  return !!data;
}


