import { supabase } from './supabaseClient.js';

function toYMD(date = new Date()) {
  // YYYY-MM-DD (local)
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

// ─── In-memory attendance cache ───────────────────────────────────────────────
// Prevents duplicate Supabase queries across components and navigation.
// Cache TTL: 5 minutes (matches typical session flows)
const CACHE_TTL_MS = 5 * 60 * 1000;
let cachedAttendance = null; // { employeeName: string, completed: boolean, timestamp: number }

/**
 * Set the attendance cache immediately (used after successful submission).
 * @param {boolean} value - Whether attendance is completed
 * @param {string} employeeName - The employee name this result applies to
 */
export function setAttendanceCache({ completed, employeeName }) {
  cachedAttendance = {
    employeeName,
    completed: !!completed,
    timestamp: Date.now(),
  };
}

/**
 * Get cached attendance result if valid (same employee + within TTL).
 * @param {string} employeeName
 * @returns {{ completed: boolean } | null}
 */
function getValidCache(employeeName) {
  if (!cachedAttendance) return null;
  if (cachedAttendance.employeeName !== employeeName) return null;
  if (Date.now() - cachedAttendance.timestamp > CACHE_TTL_MS) {
    cachedAttendance = null;
    return null;
  }
  return { completed: cachedAttendance.completed };
}

// This file writes to the following existing Supabase tables:
// - login
// - attendance_completions
// - app_logs
//
// Assumptions based on your provided schema:
// login fields: id (uuid), created_at (auto), Location (text), Emp_name (text), IP (text)
// attendance_completions fields: id (uuid), created_at (auto), Location (text), device_id (text), "Employee name" (text)
//
// IMPORTANT:
// - created_at is autogenerated in Supabase.
// - We do NOT send created_at.

// NOTE: The `day` parameter is intentionally ignored for now because your actual schema
// (as you provided) does not include a login_day/attendance_day column.

export async function upsertLoginActivity({ location, employeeName, ip } = {}) {
  if (!location) throw new Error('location is required');
  if (!employeeName) throw new Error('employeeName is required');
  if (!ip) throw new Error('ip is required');

  // Since your schema description does not list a unique constraint,
  // we do a plain insert.
  const { error } = await supabase.from('login').insert({
    Location: String(location),
    Emp_name: String(employeeName),
    IP: String(ip),
  });

  if (error) throw error;
  return { ok: true };
}

export async function upsertAttendanceCompletion({ location, deviceId, employeeName, selfieImage, stallImage, ipAddress } = {}) {
  if (!location) throw new Error('location is required');
  if (!deviceId) throw new Error('deviceId is required');
  if (!employeeName) throw new Error('employeeName is required');

  // Since your schema description does not list a unique constraint,
  // we do a plain insert.
  const { error } = await supabase.from('attendance_completions').insert({
    Location: String(location),
    device_id: String(deviceId),
    'Employee name': String(employeeName),
    'Selfie Image': selfieImage || null,
    'Stall Image': stallImage || null,
    'IP Address': ipAddress || null,
  });

  if (error) throw error;
  return { ok: true };
}

export async function isAttendanceCompletedForDevice({ deviceId } = {}) {
  if (!deviceId) throw new Error('deviceId is required');

  // Without a date column in the provided schema, we can only check existence.
  const { data, error } = await supabase
    .from('attendance_completions')
    .select('id')
    .eq('device_id', String(deviceId))
    .maybeSingle();

  if (error) throw error;
  return !!data;
}

/**
 * Check if attendance has been completed for a given employee today (IST).
 * Queries the attendance_completions table by Employee Name + Today's Date.
 *
 * Per PRD v2.0:
 * - Searches for a record matching Employee Name + Today's Date (IST)
 * - Returns only one matching record (LIMIT 1)
 * - The attendance_completions table is the single source of truth
 *
 * @param {Object} params
 * @param {string} params.employeeName - The employee name to check
 * @returns {Promise<boolean>} - True if attendance exists for today
 */
export async function checkTodayAttendance({ employeeName } = {}) {
  if (!employeeName) throw new Error('employeeName is required');

  // Return cached result if available (avoids duplicate Supabase queries)
  const cached = getValidCache(employeeName);
  if (cached !== null) {
    console.log('[AttendanceCache] Hit for', employeeName, '→', cached.completed);
    return cached.completed;
  }

  console.log('[AttendanceCache] Miss for', employeeName, '→ fetching from Supabase');
  const { data, error } = await supabase
    .from('attendance_completions')
    .select('id')
    .eq('Employee name', String(employeeName))
    .gte('created_at', new Date(new Date().toDateString()).toISOString()) // start of today UTC
    .lt('created_at', new Date(new Date(Date.now() + 86400000).toDateString()).toISOString()) // start of tomorrow UTC
    .limit(1);

  if (error) {
    console.error('[Supabase] checkTodayAttendance error:', error);
    throw error;
  }

  const completed = data && data.length > 0;

  // Store in cache for subsequent calls
  cachedAttendance = {
    employeeName,
    completed,
    timestamp: Date.now(),
  };

  return completed;
}


