import { supabase } from './supabaseClient.js';

function toYMD(date = new Date()) {
  // YYYY-MM-DD (local)
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

// ─── Attendance cache (localStorage-backed) ──────────────────────────────────
// Uses localStorage so the cache survives full page reloads (window.location.assign).
// Cache TTL: 5 minutes (matches typical session flows)
const CACHE_TTL_MS = 5 * 60 * 1000;
const CACHE_KEY = 'softy.attendanceCache';

/**
 * Set the attendance cache in localStorage (used after successful submission).
 * @param {boolean} value - Whether attendance is completed
 * @param {string} employeeName - The employee name this result applies to
 */
export function setAttendanceCache({ completed, employeeName }) {
  const truthy = !!completed;
  const entry = {
    employeeName,
    completed: truthy,
    timestamp: Date.now(),
  };
  try {
    localStorage.setItem(CACHE_KEY, JSON.stringify(entry));
    // Also sync the old localStorage flag used by isAttendanceCompleted() in storage.js
    // so that pages like Opening, Closing, etc. see the updated status immediately.
    localStorage.setItem('softy.attendanceCompleted', JSON.stringify(truthy));
  } catch {
    // localStorage might be full or unavailable; ignore
  }
}

/**
 * Get cached attendance result if valid (same employee, within TTL, not yet expired).
 * @param {string} employeeName
 * @returns {{ completed: boolean } | null}
 */
function getValidCache(employeeName) {
  try {
    const raw = localStorage.getItem(CACHE_KEY);
    if (!raw) return null;
    const entry = JSON.parse(raw);
    if (entry.employeeName !== employeeName) return null;
    if (Date.now() - entry.timestamp > CACHE_TTL_MS) {
      localStorage.removeItem(CACHE_KEY);
      return null;
    }
    return { completed: entry.completed };
  } catch {
    localStorage.removeItem(CACHE_KEY);
    return null;
  }
}

/**
 * Clear the attendance cache (e.g., on logout).
 */
export function clearAttendanceCache() {
  try {
    localStorage.removeItem(CACHE_KEY);
  } catch {
    // ignore
  }
}

// This file writes to the following existing Supabase tables:
// - login
// - attendance_completions
// - app_logs
//
// Assumptions based on your provided schema:
// login fields: id (uuid), created_at (auto), Location (text), Emp_name (text), IP (text)
// attendance_completions fields: id (uuid), created_at (auto), Location (text), device_id (text), "Employee name" (text)
//
// IMPORTANT:
// - created_at is autogenerated in Supabase.
// - We do NOT send created_at.

// NOTE: The `day` parameter is intentionally ignored for now because your actual schema
// (as you provided) does not include a login_day/attendance_day column.

export async function upsertLoginActivity({ location, employeeName, ip } = {}) {
  if (!location) throw new Error('location is required');
  if (!employeeName) throw new Error('employeeName is required');
  if (!ip) throw new Error('ip is required');

  // Since your schema description does not list a unique constraint,
  // we do a plain insert.
  const { error } = await supabase.from('login').insert({
    Location: String(location),
    Emp_name: String(employeeName),
    IP: String(ip),
  });

  if (error) throw error;
  return { ok: true };
}

export async function upsertAttendanceCompletion({ location, deviceId, employeeName, selfieImage, stallImage, ipAddress } = {}) {
  if (!location) throw new Error('location is required');
  if (!deviceId) throw new Error('deviceId is required');
  if (!employeeName) throw new Error('employeeName is required');

  // Since your schema description does not list a unique constraint,
  // we do a plain insert.
  const { error } = await supabase.from('attendance_completions').insert({
    Location: String(location),
    device_id: String(deviceId),
    'Employee name': String(employeeName),
    'Selfie Image': selfieImage || null,
    'Stall Image': stallImage || null,
    'IP Address': ipAddress || null,
  });

  if (error) throw error;
  return { ok: true };
}

export async function isAttendanceCompletedForDevice({ deviceId } = {}) {
  if (!deviceId) throw new Error('deviceId is required');

  // Without a date column in the provided schema, we can only check existence.
  const { data, error } = await supabase
    .from('attendance_completions')
    .select('id')
    .eq('device_id', String(deviceId))
    .maybeSingle();

  if (error) throw error;
  return !!data;
}

/**
 * Check if attendance has been completed for a given employee today (IST).
 * Queries the attendance_completions table by Employee Name + Today's Date.
 *
 * @param {Object} params
 * @param {string} params.employeeName - The employee name to check
 * @param {boolean} [params.bypassCache] - If true, skips cache and fetches from Supabase directly (used by polling)
 * @returns {Promise<boolean>} - True if attendance exists for today
 */
export async function checkTodayAttendance({ employeeName, bypassCache } = {}) {
  if (!employeeName) throw new Error('employeeName is required');

  // Return cached result if available — but ONLY for positive (true) results.
  // Negative results (false) always re-fetch to support polling detecting the newly created record.
  if (!bypassCache) {
    const cached = getValidCache(employeeName);
    if (cached !== null) {
      console.log('[AttendanceCache] Hit for', employeeName, '→', cached.completed);
      return cached.completed;
    }
  }

  console.log('[AttendanceCache] Miss for', employeeName, '→ fetching from Supabase');
  const { data, error } = await supabase
    .from('attendance_completions')
    .select('id')
    .eq('Employee name', String(employeeName))
    .gte('created_at', new Date(new Date().toDateString()).toISOString()) // start of today UTC
    .lt('created_at', new Date(new Date(Date.now() + 86400000).toDateString()).toISOString()) // start of tomorrow UTC
    .limit(1);

  if (error) {
    console.error('[Supabase] checkTodayAttendance error:', error);
    throw error;
  }

  const completed = data && data.length > 0;

  // Only cache positive (true) results. False results should always re-fetch
  // so that polling and subsequent checks can detect when attendance is completed.
  if (completed) {
    setAttendanceCache({ completed: true, employeeName });
  }

  return completed;
}


